quantidadeCentavos = int(input('Digite a quantidade de centavos: '))
print(f'Quantidade total de centavos: {quantidadeCentavos}')
moedas50 = int(quantidadeCentavos / 50)
quantidadeCentavos = int(quantidadeCentavos - (moedas50 * 50))
moedas25 = int(quantidadeCentavos / 25)
quantidadeCentavos = int(quantidadeCentavos - (moedas25 * 25))
moedas10 = int(quantidadeCentavos / 10)
quantidadeCentavos = int(quantidadeCentavos - (moedas10 * 10))
moedas5 = int(quantidadeCentavos / 5)
quantidadeCentavos = int(quantidadeCentavos - (moedas5 * 5))
print(f'\nmoedas de 50 centavos:{moedas50}\nmoedas de 25 centavos:{moedas25}\nmoedas de 10 centavos:{moedas10}\nmoedas de 5 centavos:{moedas5}\nmoedas de 1 centavo:{quantidadeCentavos}')